# Generated by Django 4.1.7 on 2023-03-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='User',
        ),
    ]
